import { useState, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Files from "@/components/Files";
import SideNavbar from "@/components/SideNavbar";
import SearchBar from "@/components/SearchBar";
import Button from "@/components/Button";

import { IoNotificationsCircleOutline } from "react-icons/io5";
import { CgProfile } from "react-icons/cg";

export default function Home() {
  const [file, setFile] = useState("");
  const [cid, setCid] = useState("");
  const [uploading, setUploading] = useState(false);

  const inputFile = useRef(null);

  const uploadFile = async (fileToUpload) => {
    try {
      setUploading(true);
      const formData = new FormData();
      formData.append("file", fileToUpload, fileToUpload.name);
      const res = await fetch("/api/files", {
        method: "POST",
        body: formData,
      });
      const ipfsHash = await res.text();
      setCid(ipfsHash);
      setUploading(false);
    } catch (e) {
      console.log(e);
      setUploading(false);
      alert("Trouble uploading file");
    }
  };

  const handleChange = (e) => {
    setFile(e.target.files[0]);
    // uploadFile(e.target.files[0]);
  };

  const loadRecent = async () => {
    try {
      const res = await fetch("/api/files");
      const json = await res.json();
      setCid(json.ipfs_pin_hash);
    } catch (e) {
      console.log(e);
      alert("trouble loading files");
    }
  };

  return (
    <>
      <Head>
        <title>Divvy-It</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="flex w-full">
        <SideNavbar />
        <main className="md:w-1/2 w-full min-h-screen m-auto flex flex-col justify-start items-center">
          <div className="w-full flex flex-col gap-6 p-8">
            <div className="flex w-full h-full justify-between items-center md:gap-16 gap-2">
              <SearchBar />
              <div className="flex items-center h-full gap-1 max-md:hidden">
                <IoNotificationsCircleOutline className='text-4xl text-gray-900' />
                <CgProfile className='text-3xl text-gray-900' />
              </div>
            </div>
            <input
              type="file"
              id="file"
              ref={inputFile}
              onChange={handleChange}
              className="border-2 border-gray-900 p-2 text-gray-900 rounded-md"
            />
            <div className="flex gap-4">
              <Button onClick={uploadFile} text='Upload' />
              <Button onClick={uploadFile} text='Create Folder' />
              <Button onClick={uploadFile} text='Share' />
            </div>
            <div className="flex flex-col gap-2 mt-8">
              <p className="text-4xl font-semibold">All Files</p>
              <div className="flex flex-col gap-2">

              </div>
            </div>
            {cid && (
              <Files cid={cid} />
            )}
          </div>
        </main>
      </div>
    </>
  );
}
