import { useState, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Files from "@/components/Files";
import SideNavbar from "@/components/SideNavbar";

export default function Home() {
  const [file, setFile] = useState("");
  const [cid, setCid] = useState("");
  const [uploading, setUploading] = useState(false);

  const inputFile = useRef(null);

  const uploadFile = async (fileToUpload) => {
    try {
      setUploading(true);
      const formData = new FormData();
      formData.append("file", fileToUpload, fileToUpload.name);
      const res = await fetch("/api/files", {
        method: "POST",
        body: formData,
      });
      const ipfsHash = await res.text();
      setCid(ipfsHash);
      setUploading(false);
    } catch (e) {
      console.log(e);
      setUploading(false);
      alert("Trouble uploading file");
    }
  };

  const handleChange = (e) => {
    setFile(e.target.files[0]);
    uploadFile(e.target.files[0]);
  };

  const loadRecent = async () => {
    try {
      const res = await fetch("/api/files");
      const json = await res.json();
      setCid(json.ipfs_pin_hash);
    } catch (e) {
      console.log(e);
      alert("trouble loading files");
    }
  };

  return (
    <>
      <Head>
        <title>Divvy-It</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <main className="w-full min-h-screen m-auto flex flex-col justify-center items-center">
      <div className="w-1/2 flex flex-col gap-6">
                <h1>Pinata + Next.js</h1>
                <p>
                  Update the <span className="py-1 px-2 rounded-md italic border-2 border-accent">.env.local</span> file to set your
                  Pinata API key and (optionally) your IPFS gateway URL, restart the
                  app, then click the Upload button and you'll see uploads to IPFS
                  just work™️. If you've already uploaded files, click Load recent to
                  see the most recently uploaded file.
                </p>
                <input
                  type="file"
                  id="file"
                  ref={inputFile}
                  onChange={handleChange}
                  style={{ display: "none" }}
                />
                <div>
                  <button onClick={loadRecent} className="mr-10 w-[150px] bg-light text-secondary border-2 border-secondary rounded-3xl py-2 px-4 hover:bg-secondary hover:text-light transition-all duration-300 ease-in-out">
                    Load recent
                  </button>
                  <button
                    disabled={uploading}
                    onClick={() => inputFile.current.click()}
                    className="w-[150px] bg-secondary text-light rounded-3xl py-2 px-4 hover:bg-accent hover:text-light transition-all duration-300 ease-in-out"
                  >
                    {uploading ? "Uploading..." : "Upload"}
                  </button>
                </div>
                {cid && (
                  <Files cid={cid} />
                )}
              </div>
          </main>
    </>
  );
}
